name: "arrs"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  sonarr:
    image: "11notes/sonarr:4.0.16"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "sonarr.etc:/sonarr/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "3000:8989/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  sonarr.etc:

networks:
  frontend: